### ISSUE TITLE
LBW Bayesian Modelling Code - General - output/input file

### ISSUE THREAD

**Issue by LOPEZ-Gerard** [WorldHealthOrganization/mca-pretermbirths-analysis#1]
..\mca-pretermbirths-analysis\LBW Bayesian Modelling Code\output\regionCodesOther.RDS is already in the output folder before code is run when it feels like output folder should be empty.  Also, it looks like an input rather than an output based on code. 

Can/should it be moved to inputs folder?

Referenced in:
1. 4.countryRegionalAndGlobalRatesAndNumbers.R
2. 6.subgroupMeta.R

**Comment by ellenBradley18** [comment]
I've moved this into inputs thanks!
