### ISSUE TITLE
LBW Bayesian Modelling Code - 3.fitModels.R - Error - Destination folder missing

### ISSUE THREAD

**Issue by LOPEZ-Gerard** [WorldHealthOrganization/mca-pretermbirths-analysis#10]
I received the error below and corrected it by adding a folder called "models" in output folder.

Here is the error:

> 4: There was 1 warning in \`mutate()\`.
> ℹ In argument: \`literacy_femT = ifelse(literacy_fem > 100, log(100 - 99.99999), log(100 - literacy_fem))\`.
> Caused by warning in \`log()\`:
> ! NaNs produced 
> 5: In gzfile(file, mode) :
>   cannot open compressed file 'output/models/pCCFullModel800.RDS', probable reason 'No such file or directory'

**Comment by ellenBradley18** [comment]
Added the `models` folder into the `output` folder in commit `Tidying Up`, thanks!
