### ISSUE TITLE
LBW Bayesian Modelling Code - 3.fitModels.R - Warning - Log problem

### ISSUE THREAD

**Issue by LOPEZ-Gerard** [WorldHealthOrganization/mca-pretermbirths-analysis#11]
I can’t see a problem in input data nor output…Not sure why NaNs are produced or if it has any impact downstream.

Here is the warning:

> source("3.fitModels.R")
> Skipping install of 'distortr' from a github remote, the SHA1 (32474656) has not changed since last install.
>   Use \`force = TRUE\` to force installation
> Running model.
> Total iterations: 1200, Burn in: 1000, Thinning: 1
> Something hasn't converged HAS IT.
> Max Rhat is 17.8134681157874 
> saving to RDS.
> returning the model 
> finished modelling!Warning message: 
> There was 1 warning in \`mutate()\`.
> ℹ In argument: \`literacy_femT = ifelse(literacy_fem > 100, log(100 - 99.99999), log(100 - literacy_fem))\`.
> Caused by warning in \`log()\`:
> ! NaNs produced

**Comment by ellenBradley18** [comment]
I've suppressed this warning thanks, I can't see an issue either!
