### ISSUE TITLE
LBW Bayesian Modelling Code - 4.countryRegionalAndGlobalRatesAndNumbers.R - Error - wpp_lb

### ISSUE THREAD

**Issue by LOPEZ-Gerard** [WorldHealthOrganization/mca-pretermbirths-analysis#13]
This concerns Line #541 mutate(numbers=round(wpp_lb*inv.logit(mu),0)) %>% 

When I first saw this issue there wasn’t a “wpp_lb” but rather wpp_lb.x and wpp_lb.y .  They look to be the same, but not clear. 

So I tried to use wpp_lb.y because that comes from wpp2 which seems to be what is being added here.

But when I switched it that didn't work either because there are 7 regions/loops and one must have some difference in wpp_lb that is not allowing it to be merged….but other regions earlier in the loop are fine.

And it turned out the problematic loop is "i == 7"

Not sure what the deeper problem is so that needs to be addressed.

In the end, I added this so I could proceed with testing: 
```
  if (i==7){
    data3 <- data3 %>% 
      rename("wpp_lb" = "wpp_lb.x")
    data3 <- data3 %>% 
      dplyr::select(-wpp_lb.y)
  }
```

**Comment by ellenBradley18** [comment]
Thank you for this! I have amended the code slightly to tidy it up.
