### ISSUE TITLE
LBW Bayesian Modelling Code - 6.subgroupMeta.R - Error - wpp2

### ISSUE THREAD

**Issue by LOPEZ-Gerard** [WorldHealthOrganization/mca-pretermbirths-analysis#15]
wpp2 already exists as a dataframe.  and “../output/wpp2.rds”  doesn’t exist.  

Also in first mention wpp2.rds is filtered down to 2020 only.  

To get code to run, and to not overwrite existing wpp2, I changed the offending line to use existing wpp2 as source and renamed output to wpp2020.  

I then updated all subsequent references from wpp2 to wpp2020 as well.  

One exception is lin3 #737 “wpp2<-readRDS("output/wpp2.RDS")”  which I commented out because there are no further references to wpp2 in the file. 

Here is the first error:

```
 wpp2<-readRDS("output/wpp2.rds") %>% 
+   filter(year==2020)
Error in gzfile(file, "rb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file 'output/wpp2.rds', probable reason 'No such file or directory'
```

**Comment by ellenBradley18** [comment]
Great thank you for fixing this!
