### ISSUE TITLE
LBW Bayesian Modelling Code - 6.subgroupMeta.R - Error - pCCFullModel_16000 vs. pCCFullModel_800

### ISSUE THREAD

**Issue by LOPEZ-Gerard** [WorldHealthOrganization/mca-pretermbirths-analysis#16]
This error occurs because this code file is expecting a file to exist as output from one of the previous code files.  
Unfortunately the file was not produced by the other code, but rather one with “800” in the middle. 

It is not clear at all why my run of the code results in "pCCFullModel_800" whereas obviously previous runs of the code result in "pCCFullModel_16000" files. Or if there is a difference between these two.

Temporarily changing line #178 to be able to proceed. Also line #729.

Here is the first error:

```
#Read in the latest estimates
> rGLBW<-read.csv("output/pCCFullModel_16000_regionalAndGlobalEstimates.csv") %>% 
+   filter(year==2020) %>% dplyr::select(regionName, estN, estNU, 
+                                        estNL, est) %>% 
+   rename(wpp_lb=estN) 
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'output/pCCFullModel_16000_regionalAndGlobalEstimates.csv': No such file or directory
```

**Comment by ellenBradley18** [comment]
Updated the number of iterations in "3.fitModel.R" in the "Tidying Up" commit, thank you!
