### ISSUE TITLE
LBW Bayesian Modelling Code - Testing Run 2023-07-28 - Final Comments

### ISSUE THREAD

**Issue by LOPEZ-Gerard** [WorldHealthOrganization/mca-pretermbirths-analysis#18]
I finished the main testing run for today/yesterday. And here are my final comments about it.

1.	Main concern is that what seems like the final output produced doesn’t match the naming of the final output that I have seen.  Namely that they have the prefix of pCCFullModel_800 rather than pCCFullModel_16000.

2.	The output below was produced with the changes described in the various issues and installation of JAGS-4.3.1.exe from http://www.sourceforge.net/projects/mcmc-jags/files.   You will have to say whether this is what was expected or not from these inputs and code file.

3. FINAL OUTPUT FILES:

..\output\adminWithoutBirthEstFB80HMIS.csv
..\output\allDataInc.RDS
..\output\allMetaEsts.csv
..\output\dqc5_CountryFlag.RDS
..\output\DQC5criteria_calculations.csv
..\output\DQC5Update_countries.csv
..\output\Figure4table-heightOrder.csv
..\output\finalData.RDS
..\output\latestMetaEsts.csv
..\output\LBW subgroup.pdf
..\output\modelVal.RDS
..\output\pCCFullModel_800_Coefficients.csv
..\output\pCCFullModel_800_Estimates.csv
..\output\pCCFullModel_800_modelSummary.csv
..\output\pCCFullModel_800_modelValidation1000.csv
..\output\pCCFullModel_800_modelValidation1000.RDS
..\output\pCCFullModel_800_regionalAndGlobalEstimates.csv
..\output\pCCFullModel_800_table2.csv
..\output\pCCFullModel_800_tracePlots.pdf
..\output\regionCodes.RDS
..\output\Table 10 - Meta Subgroup (applying total to LBW rates).csv
..\output\Table 10 - Meta Subgroup (NA applied to all).csv
..\output\models\pCCFullModel_modelVal800.RDS
..\output\models\pCCFullModel800.RDS

**Comment by ellenBradley18** [comment]
I have fixed issue 1, added issue 2 in the `readMe` and `loadPackages.R` and reduced the number of outputs and renamed them to align with the `Quick Access` files.
