### ISSUE TITLE
LBW Bayesian Modelling Code - 0.master.R

### ISSUE THREAD

**Issue by LOPEZ-Gerard** [WorldHealthOrganization/mca-pretermbirths-analysis#2]
Missing these R files?:

1. 8.Figures for paper.R
2. 8.Numbers for paper.R
3. 8.LBWinclusionExclusionFlow.R

These files unused?:

1. 3.fitModels_biasInform.R

**Comment by ellenBradley18** [comment]
Removed as not needed as discussed!
