### ISSUE TITLE
Preterm Bayesian Modelling Code - General - output/input files

### ISSUE THREAD

**Issue by LOPEZ-Gerard** [WorldHealthOrganization/mca-pretermbirths-analysis#20]
..\mca-pretermbirths-analysis\\Preterm Bayesian Modelling Code\output\ already has files in the output folder before code is run when it feels like output folder should be empty. Also, they look like inputs rather than outputs based on code.

Can/should it be moved to inputs folder?
The files are:

1. regionCodes.RDS
2. regionCodesOther.RDS
3. wpp2.rds

Referenced in:

3.fitModelsP_singMultDQC.R
4.countryR&GratesandNumbers.R
6.subgroupsMetaP.R
functions\runModelValidationP.R

**Comment by ellenBradley18** [comment]
I've moved them over in commit `Tidying Up (3)` thanks!
