### ISSUE TITLE
Preterm Bayesian Modelling Code - 1.combineAdminandSurvey2.R - Warning - empty addOn2 

### ISSUE THREAD

**Issue by LOPEZ-Gerard** [WorldHealthOrganization/mca-pretermbirths-analysis#27]
This one is likely fine as well, but addOn2 is empty with only 11 columns and no rows.
So adminAll2 has the columns now, but they contain nothing...which is probably what was desired, but it did throw a warning.

Here is the warning:

```
> adminAll2<-cbind(adminAll, addOn2)
Warning message:
In data.frame(..., check.names = FALSE) :
  row names were found from a short variable and have been discarded
```

**Comment by ellenBradley18** [comment]
I have changed this section so hopefully the warnings don't appear. 
If it works, please can you remove lines 3-18 on this!
