### ISSUE TITLE
LBW Bayesian Modelling Code - 0.loadPackages.R

### ISSUE THREAD

**Issue by LOPEZ-Gerard** [WorldHealthOrganization/mca-pretermbirths-analysis#3]
There were some packages missing from this file that appeared in the headings of the other files.

In the end, I updated 0.loadPackages.R to include every package in all of the files, and commented out the other library statements in the code files and everything seems to run ok.

But there is a special point in that we seem to need to have to install JAGS library from [http://www.sourceforge.net/projects/mcmc-jags/files](http://www.sourceforge.net/projects/mcmc-jags/files) .

Maybe we need to add that to the documentation somewhere?

**Comment by ellenBradley18** [comment]
Great thank you for tidying the loadPackages files up! 
I have added the note about the separate JAGs download in the readME and the loadPackages files in `Tidying Up` commit.
