### ISSUE TITLE
Preterm Bayesian Modelling Code - 5. Plot countries P (1 model) 1 plot.R - file missing

### ISSUE THREAD

**Issue by LOPEZ-Gerard** [WorldHealthOrganization/mca-pretermbirths-analysis#31]
Unfortunately it seems like the file "5. Plot countries P (1 model) 1 plot.R" is missing from the repo.
It is in 0.masterP.R. I have tried running the remaining files without having run "5. Plot countries P (1 model) 1 plot.R" first and there are several problems as documented in further issues.

Error: 
```
> source("5. Plot countries P (1 model) 1 plot.R")
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file '5. Plot countries P (1 model) 1 plot.R': No such file or directory
```

**Comment by ellenBradley18** [comment]
Removed this as it isn't needed as discussed!
