### ISSUE TITLE
Preterm Bayesian Modelling Code - 6.subgroupsMetaP.R - duplicate calls to source

### ISSUE THREAD

**Issue by LOPEZ-Gerard** [WorldHealthOrganization/mca-pretermbirths-analysis#32]
There are two calls to source in this file to files that have already successfully run. Is this needed?  "0.fileNames.R" and "1.cleanSurveyP2.R" are basic files that are setting all the subsequent files up, so it doesn't seem necessary to run them again at this point.

Here are the lines:

```
source("0.fileNames.R")
source("1.cleanSurveyP2.R")
```

**Comment by ellenBradley18** [comment]
I have commented these out thank you! If you run all the code at once you shouldnt need to rerun these. Depending on the size of the machine used a user might need to clear the workspace when doing the regional groupings so I will keep this in and make a note if that's the case!
