### ISSUE TITLE
Preterm Bayesian Modelling Code - 0.loadPackages.R / 6.subgroupsMetaP.R - Error - library calls

### ISSUE THREAD

**Issue by LOPEZ-Gerard** [WorldHealthOrganization/mca-pretermbirths-analysis#34]
It seems like library(gridGraphics) is needed for 6.subgroupsMetaP.R to run, so I have added it to 0.loadPackages.R.  I also copied all of the library calls from the other assorted files and made sure they were all present in 0.loadPackages.R.

Here is the error: 

```
> grid.text("Preterm<28 weeks / Preterm<37 weeks", 0.5, 0.97, gp=gpar(cex=1))
Error in grid.text("Preterm<28 weeks / Preterm<37 weeks", 0.5, 0.97, gp = gpar(cex = 1)) : 
  could not find function "grid.text"
```

**Comment by ellenBradley18** [comment]
great thanks!
