### ISSUE TITLE
Preterm Bayesian Modelling Code -Testing Run 2023-08-08 - Final Comments

### ISSUE THREAD

**Issue by LOPEZ-Gerard** [WorldHealthOrganization/mca-pretermbirths-analysis#35]
I finished the main testing run for today/yesterday. And here are my final comments about it.

1. Main concern is that what seems like the final output produced doesn’t match the naming of the final output that I have seen. Namely that they have the prefix of pCCFullModel_800 rather than pCCFullModel_16000. [IGNORE THIS COMMENT IT COMES FROM LBW]

2. The output below was produced with the changes described in the various "Preterm Bayesian Modelling Code " issues and installation of JAGS-4.3.1.exe from http://www.sourceforge.net/projects/mcmc-jags/files. You will have to say whether this is what was expected or not from these inputs and code file.

3. The most obvious problem I have is that one of the source files that is referenced in 0.masterP.R, "5. Plot countries P (1 model) 1 plot.R", is not present in the Repo, so it is not clear how that impacts the final output.

4. I also only ran 7. splineModelsValidationP.R with nreps=1 so that I could finish review.  So it is not fully tested.
 
5. FINAL OUTPUT FILES:

..\Preterm Bayesian Modelling Code\output\models\pCCFullModelP_dataType1DQC1_TEST_modelVal16000.RDS
..\Preterm Bayesian Modelling Code\output\models\pCCFullModelP_dataType1DQC1_TEST16000.RDS
..\Preterm Bayesian Modelling Code\output\DQC4_calculations.csv
..\Preterm Bayesian Modelling Code\output\DQC4_countries.csv
..\Preterm Bayesian Modelling Code\output\finalPreterm.RDS
..\Preterm Bayesian Modelling Code\output\finalPreterm_MGA.rds
..\Preterm Bayesian Modelling Code\output\methodGACountries.csv
..\Preterm Bayesian Modelling Code\output\missingSourceSubType.csv
..\Preterm Bayesian Modelling Code\output\modelVal.RDS
..\Preterm Bayesian Modelling Code\output\pCCFullModelP_dataType1DQC1_TEST_16000_Estimates.csv
..\Preterm Bayesian Modelling Code\output\pCCFullModelP_dataType1DQC1_TEST_16000_Figure3data.csv
..\Preterm Bayesian Modelling Code\output\pCCFullModelP_dataType1DQC1_TEST_16000_Figure4editable.pptx
..\Preterm Bayesian Modelling Code\output\pCCFullModelP_dataType1DQC1_TEST_16000_Figure4table-reorder.csv
..\Preterm Bayesian Modelling Code\output\pCCFullModelP_dataType1DQC1_TEST_16000_modelSummary.csv
..\Preterm Bayesian Modelling Code\output\pCCFullModelP_dataType1DQC1_TEST_16000_modelValidation1.csv
..\Preterm Bayesian Modelling Code\output\pCCFullModelP_dataType1DQC1_TEST_16000_modelValidation1.rds
..\Preterm Bayesian Modelling Code\output\pCCFullModelP_dataType1DQC1_TEST_16000_pretermSubgroupForest.pdf
..\Preterm Bayesian Modelling Code\output\pCCFullModelP_dataType1DQC1_TEST_16000_regionalAndGlobalEstimates.csv
..\Preterm Bayesian Modelling Code\output\pCCFullModelP_dataType1DQC1_TEST_16000_Table 10 - Preterm Meta Subgroup (applying total to all regions).csv
..\Preterm Bayesian Modelling Code\output\pCCFullModelP_dataType1DQC1_TEST_16000_table2.csv
..\Preterm Bayesian Modelling Code\output\pCCFullModelP_dataType1DQC1_TEST_16000_tracePlots.pdf
..\Preterm Bayesian Modelling Code\output\Preterm subgroups.rds
..\Preterm Bayesian Modelling Code\output\pretermPreIncExc.rds

**Comment by ellenBradley18** [comment]
Thanks very much for these! I have reduced the number of outputs so only the essential outputs are there. 
The other unnecessary files you mentioned have been removed as discussed. All in the `Tidying up (2)` commit.
