### ISSUE TITLE
Overall - Final Databases / Misc. Files - Final Comments 

### ISSUE THREAD

**Issue by LOPEZ-Gerard** [WorldHealthOrganization/mca-pretermbirths-analysis#37]
One is that I can forsee is that similar to the files in the "Preterm Regional Groupings" and "LBW Regional Groupings" folders, there are multiple "Final Database" files in the main folder, but how were they generated?  They seem to be output of some code, but where is that code?

The files in question:
..\mca-pretermbirths-analysis\LBWcovariates.csv
..\mca-pretermbirths-analysis\LBWcovariates.rds
..\mca-pretermbirths-analysis\LBWfinalDatabase.csv
..\mca-pretermbirths-analysis\LBWfinalDatabase.rds
..\mca-pretermbirths-analysis\PretermfinalDatabase.csv
..\mca-pretermbirths-analysis\PretermfinalDatabase.rds

**Comment by ellenBradley18** [comment]
Thanks for this! They are produced in the code so are outputted into the `outputs` folder, they are finalData and finalPreterm for LBW and Preterm respectively. A lot of code would need to be change to change these names, so I have added this detail into the readMe file (in commit `Tidying up (2)`- is this clear or does it need a different solution?

**Comment by LOPEZ-Gerard** [comment]
@ellenBradley18  I think it will be ok if you make it clear on the read me on the first page for the project (and maybe with another read me in this folder) that the files that are in the folder are the results of the code and match the files the code will generate and place in  LBW Bayesian Modelling Code/output folder.

As long as we can clearly see where the files came from it should be fine.

That being said, if I look for LBWfinalInputDatabase.csv or LBWfinalInputDatabase.rds in the LBW Bayesian Modelling Code/input folder, I can't find it.   Does it have a different name there? If so, that needs to be made clear somewhere. Either in the read mes, or....even better I would think is to change the name of the file in the LBW Bayesian Modelling Code/input folder to match the Quick Access folder file name.  You would need to slightly change the code files that reference it, but I think it would be a simple change that would help a lot with clarity. 

But that's just my opinion (and maybe I am misunderstanding the function of these files.)

**Comment by ellenBradley18** [comment]
I have amended the code so that the final input databases that are created in the code and written into the `output` folders have the same name as the `Quick Access` final input databases!
