### ISSUE TITLE
LBW Bayesian Modelling Code - 0.fileNames.R - path error

### ISSUE THREAD

**Issue by LOPEZ-Gerard** [WorldHealthOrganization/mca-pretermbirths-analysis#4]
`Error: `path` does not exist: ‘C:/Users/EllenBradley/OneDrive – London School of Hygiene and Tropical Medicine/Documents/LBW SURVEY DATA/2022 12 01 LBW estimates combined database.xlsx’
`

I changed to surveyName<-“input/2022 12 01 LBW estimates combined database.xlsx”

**Comment by ellenBradley18** [comment]
great thank you!
