### ISSUE TITLE
LBW Bayesian Modelling Code - 1.newAdmin5.R - Warning - Excel Comment Column

### ISSUE THREAD

**Issue by LOPEZ-Gerard** [WorldHealthOrganization/mca-pretermbirths-analysis#5]
When running this code I received the warning down below.
I think that it is fine as what is happening is that the excel sheet has a column where only 14 rows have comments in them.  Because the first xxx number of rows are null, R is expecting a boolean logical data type so it doesn't like that on those 14 rows (which are thousands deep in the file I think) that there is text instead.  But I don't think that this column is used anywhere.

One small suggestion though is that the excel file is a little off as the filter does not include the column where “'EB Updated 13/12…” text appears, so if someone sorts then the comment will be associated with the wrong row.  So that excel file should be updated I think.

Here is the warning:

> > newAdmin<-readxl::read_excel(paste0(newAdminName), 
> \+                              sheet = "data", skip=1)
> New names:
> • \`\` -> \`...22\`
> • \`\` -> \`...35\`
> There were 14 warnings (use warnings() to see them) 
> > warnings()
> Warning messages:
> 1: Expecting logical in AI2103 / R2103C35: got 'EB Updated 13/12 so same as what went to CC'
> 2: Expecting logical in AI2104 / R2104C35: got 'EB Updated 13/12 so same as what went to CC'
> 3: Expecting logical in AI2105 / R2105C35: got 'EB Updated 13/12 so same as what went to CC'
> 4: Expecting logical in AI2106 / R2106C35: got 'EB Updated 13/12 so same as what went to CC'
> 5: Expecting logical in AI2107 / R2107C35: got 'EB Updated 13/12 so same as what went to CC'
> 6: Expecting logical in AI2108 / R2108C35: got 'EB Updated 13/12 so same as what went to CC'
> 7: Expecting logical in AI2109 / R2109C35: got 'EB Updated 13/12 so same as what went to CC'
> 8: Expecting logical in AI2110 / R2110C35: got 'EB Updated 13/12 so same as what went to CC'
> 9: Expecting logical in AI2111 / R2111C35: got 'EB Updated 13/12 so same as what went to CC'
> 10: Expecting logical in AI2112 / R2112C35: got 'EB Updated 13/12 so same as what went to CC'
> 11: Expecting logical in AI2113 / R2113C35: got 'EB Updated 13/12 so same as what went to CC'
> 12: Expecting logical in AI2114 / R2114C35: got 'EB Updated 13/12 so same as what went to CC'
> 13: Expecting logical in AI2115 / R2115C35: got 'EB Updated 13/12 so same as what went to CC'
> 14: Expecting logical in AI2116 / R2116C35: got 'EB Updated 13/12 so same as what went to CC'

**Comment by ellenBradley18** [comment]
Great thank you for noting this. I have amended the spreadsheet so the filter includes all the columns and checked there were no issues. I have added a comment into the master file to ignore this warning.
