### ISSUE TITLE
LBW Bayesian Modelling Code - 1.newAdmin5.R - Warning - NA

### ISSUE THREAD

**Issue by LOPEZ-Gerard** [WorldHealthOrganization/mca-pretermbirths-analysis#6]
Probably ok as NA seems to be set where value is not a number.

Here is the warning:

> #Calculating the LBW subgroups from using the data that is already there
> > newAdmin3<-newAdmin2 %>% mutate(calculateBW=ifelse(NumberofbabieswithBW=="CL", 1, 
> \+                                                    ifelse(NumberofbabieswithBW=="NA_LBW%", 2, 0)),
> \+                                 calculateLBW=ifelse(LBWlt2500g=="CL", 1, 0),
> \+                                 calculate1000=ifelse(LBWlt1000g=="CL", 1, 0), 
> \+                                 calculate1500=ifelse(LBWlt1500g=="CL", 1, 0),
> \+                                 calculate15002499=ifelse(LBW1500to2499g=="CL", 1, 0), 
> \+                                 calculate10001999=ifelse(LBW1000to1999g=="CL", 1, 0)) %>% 
> \+   mutate_at(c(names(newAdmin2)[4:22]), as.numeric)
> Warning message:
> There were 17 warnings in `mutate()`.
> The first warning was:
> ? In argument: \`Numberoftotalbirths = .Primitive("as.double")(Numberoftotalbirths)\`.
> Caused by warning:
> ! NAs introduced by coercion

**Comment by ellenBradley18** [comment]
I've suppressed this warning thanks!
