### ISSUE TITLE
LBW Bayesian Modelling Code - 1.cleanSurvey.R - Warning - NAs

### ISSUE THREAD

**Issue by LOPEZ-Gerard** [WorldHealthOrganization/mca-pretermbirths-analysis#7]
It appears as if this is fine as NA is set where not a number

Here is the warning:

> #Tidying variables
> > surveyBefore<-surveyBefore %>% rename(
> \+                           Year=\`MidtopointforLBWestimate\`,
> \+                           iso=\`ISOCode\`,
> \+                           Countryname=Country, sourceSubTypeOther=Survey) %>% 
> \+   dplyr::select(iso,Countryname,Year, LBW_adjusted_point_est,
> \+          LBW_adjusted_se, sourceSubTypeOther, Crude_LBW_point_est, Crude_LBW_se) %>%
> \+   mutate(Year=as.numeric(Year)) %>% 
> \+   mutate(LBW_adjusted_point_est=LBW_adjusted_point_est*100,
> \+          Crude_LBW_point_est=as.numeric(Crude_LBW_point_est)*100,
> \+          LBW_adjusted_se=as.numeric(LBW_adjusted_se),
> \+          Crude_LBW_se=as.numeric(Crude_LBW_se)) %>% 
> \+   mutate(Source="Survey", sourceSubType=ifelse(sourceSubTypeOther=="DHS", 5,
> \+                                                ifelse(sourceSubTypeOther=="MICS", 6,
> \+                                                       7))) %>% 
> \+   mutate(isoYear=paste0(iso, Year))
> Warning message:
> There were 3 warnings in \`mutate()\`.
> The first warning was:
> ℹ In argument: \`Crude_LBW_point_est = as.numeric(Crude_LBW_point_est) * 100\`.
> Caused by warning:
> ! NAs introduced by coercion

**Comment by ellenBradley18** [comment]
I've suppressed this warning thanks!
