### ISSUE TITLE
LBW Bayesian Modelling Code - 1.applyingInclusionCriteria.R - Warning - ISO codes

### ISSUE THREAD

**Issue by LOPEZ-Gerard** [WorldHealthOrganization/mca-pretermbirths-analysis#8]
It appears as if the ISO - 3 and ISO - 2 codes are not being picked up, most likely because the first rows are "Global" so don't have codes so R thinks those columns are boolean / logical data types and doesn't like it when the text for the ISO codes appears in the rows with countries.
Not a big deal I think because obviously the codes get picked up later in the code/input data.

Here are the warnings:

> > #wpp_2021 <- read_dta(paste0("input/", wpp))
> > wpp_2021 <- readxl::read_xlsx(paste0("input/", wpp2))
> There were 50 or more warnings (use warnings() to see the first 50)
> > warnings()
> Warning messages:
> 1: Expecting logical in E1730 / R1730C5: got 'BDI'
> 2: Expecting logical in F1730 / R1730C6: got 'BI'
> 3: Expecting logical in E1731 / R1731C5: got 'BDI'
> 4: Expecting logical in F1731 / R1731C6: got 'BI'
> 5: Expecting logical in E1732 / R1732C5: got 'BDI'
> 6: Expecting logical in F1732 / R1732C6: got 'BI'
> 7: Expecting logical in E1733 / R1733C5: got 'BDI'
> 8: Expecting logical in F1733 / R1733C6: got 'BI'
> 9: Expecting logical in E1734 / R1734C5: got 'BDI'
> 10: Expecting logical in F1734 / R1734C6: got 'BI'
> 11: Expecting logical in E1735 / R1735C5: got 'BDI'
> 12: Expecting logical in F1735 / R1735C6: got 'BI'
> 13: Expecting logical in E1736 / R1736C5: got 'BDI'
> 14: Expecting logical in F1736 / R1736C6: got 'BI'
> 15: Expecting logical in E1737 / R1737C5: got 'BDI'
> 16: Expecting logical in F1737 / R1737C6: got 'BI'
> 17: Expecting logical in E1738 / R1738C5: got 'BDI'
> 18: Expecting logical in F1738 / R1738C6: got 'BI'
> 19: Expecting logical in E1739 / R1739C5: got 'BDI'
> 20: Expecting logical in F1739 / R1739C6: got 'BI'
> 21: Expecting logical in E1740 / R1740C5: got 'BDI'
> 22: Expecting logical in F1740 / R1740C6: got 'BI'
> 23: Expecting logical in E1741 / R1741C5: got 'BDI'
> 24: Expecting logical in F1741 / R1741C6: got 'BI'
> 25: Expecting logical in E1742 / R1742C5: got 'BDI'
> 26: Expecting logical in F1742 / R1742C6: got 'BI'
> 27: Expecting logical in E1743 / R1743C5: got 'BDI'
> 28: Expecting logical in F1743 / R1743C6: got 'BI'
> 29: Expecting logical in E1744 / R1744C5: got 'BDI'
> 30: Expecting logical in F1744 / R1744C6: got 'BI'
> 31: Expecting logical in E1745 / R1745C5: got 'BDI'
> 32: Expecting logical in F1745 / R1745C6: got 'BI'
> 33: Expecting logical in E1746 / R1746C5: got 'BDI'
> 34: Expecting logical in F1746 / R1746C6: got 'BI'
> 35: Expecting logical in E1747 / R1747C5: got 'BDI'
> 36: Expecting logical in F1747 / R1747C6: got 'BI'
> 37: Expecting logical in E1748 / R1748C5: got 'BDI'
> 38: Expecting logical in F1748 / R1748C6: got 'BI'
> 39: Expecting logical in E1749 / R1749C5: got 'BDI'
> 40: Expecting logical in F1749 / R1749C6: got 'BI'
> 41: Expecting logical in E1750 / R1750C5: got 'BDI'
> 42: Expecting logical in F1750 / R1750C6: got 'BI'
> 43: Expecting logical in E1751 / R1751C5: got 'BDI'
> 44: Expecting logical in F1751 / R1751C6: got 'BI'
> 45: Expecting logical in E1752 / R1752C5: got 'BDI'
> 46: Expecting logical in F1752 / R1752C6: got 'BI'
> 47: Expecting logical in E1753 / R1753C5: got 'BDI'
> 48: Expecting logical in F1753 / R1753C6: got 'BI'
> 49: Expecting logical in E1754 / R1754C5: got 'BDI'
> 50: Expecting logical in F1754 / R1754C6: got 'BI'

**Comment by ellenBradley18** [comment]
I've suppressed this warning thanks!
