### ISSUE TITLE
LBW Bayesian Modelling Code - 2.covarArray2.R - Warning - log problem

### ISSUE THREAD

**Issue by LOPEZ-Gerard** [WorldHealthOrganization/mca-pretermbirths-analysis#9]
I can’t see a problem in input data nor output…Not sure why NaNs are produced or if it has any impact downstream.

Here is the warning:

> transform<-covarset %>% mutate(gniT=log(gni),
> \+                             literacy_femT=ifelse(literacy_fem>100, log(100-99.99999), log(100-literacy_fem)),
> \+                             contraception_metT=log(1-contraception_met),
> \+                             bmi_f_underT=log(bmi_f_under),
> \+                             urbanT=urban
> \+                             #,nmrT=nmr-mean(covarset$nmr, na.rm=TRUE)
> \+                             #underweightT=underweight
> \+ )
> Warning message:
> There was 1 warning in \`mutate()\`.
> ℹ In argument: \`literacy_femT = ifelse(literacy_fem > 100, log(100 - 99.99999), log(100 -
>   literacy_fem))\`.
> Caused by warning in \`log()\`:
> ! NaNs produced

**Comment by ellenBradley18** [comment]
I've suppressed this warning thanks!
